<?php

namespace AppBundle\Repository;

/**
 * AdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdsRepository extends \Doctrine\ORM\EntityRepository
{
}
