<?php

namespace AppBundle\Repository;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesRepository extends \Doctrine\ORM\EntityRepository
{
}
