imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
      items_per_page: 10
      locale: en
      languages:
         en: English
         ru: Русский
      cck_editor_list:
        - About

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: v5
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d days'
    form:
        resources:
            - bootstrap_3_layout.html.twig
            - SonataCoreBundle:Form:datepicker.html.twig
            - AppBundle:Form:icon.html.twig

## Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ AppBundle, FOSUserBundle ]
#    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
#        scssphp:
#            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
#        jsqueeze: ~
#        less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/lib/node_modules]


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
           json: Sonata\Doctrine\Types\JsonType

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    encryption: tls
#    auth_mode:  login
#    port:  465
    logging:  "%kernel.debug%"
#    spool:     { type: memory }
## Swiftmailer Configuration
#swiftmailer:
#    transport: "%mailer_transport%"
#    host:      "%mailer_host%"
#    username:  "%mailer_user%"
#    password:  "%mailer_password%"
#    spool:     { type: memory }

fos_user:
       db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
       firewall_name: main
       use_listener: false
       user_class: AppBundle\Entity\User
       registration:
           form:
               type: AppBundle\Form\RegistrationType

# sonata block configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
#        sonata.admin.block.project.list:

# sonata admin configuration
sonata_admin:
    title:      Rental Ufa
    title_logo: /template/img/logo.png
    security:
        handler: sonata.admin.security.handler.role
    templates:
        # default global templates

        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        knp_menu_template: AppBundle:AdminMenu:custom_knp_menu.html.twig
        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        search:  SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
#        list_mosaic_custom: list_outer_rows_mosaic_custom.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            -
              position: top
              type: sonata.admin.block.admin_list
              settings:
                  groups: [Menu]
        groups:
            Menu:
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-list-alt"></i>'
                items:
                    - app.admin.regions
                    - app.admin.types
                    - app.admin.ads
                    - app.admin.disables
                    - app.admin.user
                    - app.admin.archive.user
                roles: [  ROLE_MODERATOR, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_CLIENT ]

# stfo doctrine extensions
stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            loggable: true

# tinumce
#stfalcon_tinymce:
#    include_jquery:       false
#    tinymce_jquery:       false
#    language: en
#    theme:
#          # Simple theme: same as default theme
#          simple:
#               plugins:
#                   - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#                   - "searchreplace wordcount visualblocks visualchars code fullscreen"
#                   - "insertdatetime media nonbreaking save table contextmenu directionality"
#                   - "emoticons template paste textcolor"
#               toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#               toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
#               image_advtab: true

#a2lix_translation_form:
#    locales: [en, ru]                       # [Optionnal] Array of translations locales. Can be specified in the form.
##    default_required: false
#
#a2lix_translation_form:
#    default_locale: en
#    locales: [en]
#    required_locales: [en]

jms_i18n_routing:
    default_locale: ru
    locales: [en, ru]
    strategy: prefix_except_default


# fos rest bundle
fos_rest:
    param_fetcher_listener: true
    body_listener: false
    body_converter:
                enabled: true
    format_listener: false
    view:
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false

#ivory_ck_editor:
#    configs:
#        my_config:
#            toolbar: "my_toolbar"
#            forcePasteAsPlainText: true
#    toolbars:
#        configs:
#            my_toolbar: [ "@basicstyles", "/", "@paragraph" , "/", "@links" ]
#        items:
#            basicstyles: ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat", "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote" , "Link", "Unlink"]
#            paragraph:   ~
#            links:       ~

monolog:
    channels: ["command_create", "process_error"]
    handlers:
        command_create:
            type:  stream
            path:  "%kernel.logs_dir%/command_create.log"
            channels: [command_create]
        process_error:
            type:  stream
            path:  "%kernel.logs_dir%/process_error.log"
            channels: [process_error]

#liip_imagine:
#    resolvers:
#       default:
#          web_path: ~
#
#    filter_sets:
##        cache: ~
#        banner_thumb:
#            quality: 90
#            filters:
#                thumbnail: { size: [300, 190], mode: outbound }
#        admin_mosaic:
#            quality: 80
#            filters:
#                thumbnail: { size: [ 400, 150], mode: outbound }
#        meta_image:
#            quality: 100
#            filters:
#                thumbnail: { size: [ 700, 500], mode: outbound }
#        header_image:
#            quality: 90
#            filters:
#                thumbnail: { size: [ 800, 400], mode: outbound }
#        header_phone_image:
#            quality: 90
#            filters:
#                thumbnail: { size: [ 400, 100], mode: outbound }
#        blog_image:
#            quality: 90
#            filters:
#                thumbnail: { size: [ 500, 400], mode: outbound }
#        phone_image:
#            quality: 90
#            filters:
#                thumbnail: { size: [ 600, 500], mode: outbound }
#        blog_smal:
#            quality: 90
#            filters:
#                thumbnail: { size: [ 130, 130], mode: outbound }